spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/springjwt_db
        username:
        password: 

    jpa:
        hibernate:
            ddl-auto: create
            show_sql: true
        properties:
            hibernate:
                format_sql: true
        database: postgresql

application:
    security:
        jwt:
            secret-key: 
            acces-token-expiration: 86400000
            refresh-token-expiration: 604800000
